server:
  port: 8082

spring:
  mvc:
    static-path-pattern: /static/**
  application:
    name: smartagriculture

  datasource:
    url: jdbc:mysql://localhost:3306/agricultural_management_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.qq.com
    port: 587
    username: mjxie2003@qq.com
    password: itxiaiwvdylmeaji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: MyJwtSecretKey123456
  expiration: 86400
  issuer: smart-agriculture

kaptcha:
  border: "no"
  textproducer:
    font:
      color: black
      size: 40
    char:
      length: 5
      space: 5
    noise:
      color: gray

file:
  upload-dir: ./uploads
